### ISSUE TITLE
State Diagram Flow Model

### ISSUE THREAD

**Issue by ptoulino** [Project-PICK/Project-PICK#17] opened 2020-09-26 04:38 UTC
| 💈Task: | ⚙️Description: |
| ------:| -----------:|
| Create Model  | Describe the behavior of systems |

**Comment by itravers** [comment] 2020-10-10 06:36
Isn't this kind of a duplicate of issue #25 ?

**Comment by itravers** [comment] 2020-10-16 00:04
I think it was as a duplicate of #25 , and that issue is done, so closing this one now as well.

**Closed as completed by itravers** 2020-10-16 00:04 UTC
Labels: documentation
